#!/bin/env sh
# Ansi color code variables
red="\e[0;91m"
blue="\e[0;94m"
expand_bg="\e[K"
blue_bg="\e[0;104m${expand_bg}"
red_bg="\e[0;101m${expand_bg}"
green_bg="\e[0;102m${expand_bg}"
green="\e[0;92m"
white="\e[0;97m"
bold="\e[1m"
uline="\e[4m"
reset="\e[0m"

#GLOBALS
DBFILE=~/.musicdb
HOST="127.0.0.1"
PORT="6600"
# Todo:
# Implement custom prompt from here
# fPROMPT="mpfzf >>"

# Dependency Check
if [ "$(command -v rlwrap)" ]; then
    if [ "$(command -v mpc)" ]; then
        if [ "$(command -v fzf)" ]; then
            >&2 echo -e "${green}Dependency Check was Successful${reset}"
        else
            >&2 echo -e "${red}fzf${reset} not found"
            exit 1
        fi
    else
        >&2 echo -e "${red}mpc${reset} not found"
        exit 1
    fi
else
    >&2 echo -e "${red}rlwrap${reset} not found"
    exit 1
fi

# Trap Ctrl+C to reset terminal
# To avoid it from getting messed up because of rlwrap
trap "reset; echo \"Bye!\";exit" INT
function __create_db() {
    mpc listall > $DBFILE
}

function __list() {
    mpc playlist | grep -n ".*" | less -R
}

function __quit() {
    reset
    echo -e "${green} Bye! ${reset}"
    exit
}

function __add() {
    __create_db
    mpc add "$(cat $DBFILE | fzf --reverse --prompt "mpfzf :: add >> " --height 40%)"
}

function __play() {
    mpc play $(mpc playlist | grep -n ".*" | sed "s/:/ /g" |fzf --height 40% --reverse --prompt "mpfzf :: play >> "| cut -d " " -f 1)
    sleep 1
}

function __remove() {
    mpc del $(mpc playlist | grep -n ".*" | sed "s/:/ /g" |fzf --height 40% --reverse --prompt "mpfzf :: remove >> "| cut -d " " -f 1)
    sleep 1
}
function __next() {
    mpc next
}
function __previous() {
    mpc prev
}
function __resume() {
    mpc  play
}
function __pause() {
    mpc pause
}

function __interactive() {
>&2 echo -e "Press ${red}<CTRL+C>${reset} to exit."
while :
    do
        #rlwrap sh -c "echo -e -n \"${green}Action${reset}>> \" "
        SELECTION=$(rlwrap -pGreen -S 'Action :: mpc >> ' -H '.mpd.hist' -o cat)
        #echo $SELECTION
    case $SELECTION
        in
            a   | add      )   __add ;;
            ">" | next     )   __next ;;
            "<" | previous )   __previous ;;
            r   | resume   )   __resume ;;
            p   | play     )   __play ;;
            x   | remove   )   __remove  ;;
            u   | pause    )   __pause ;;
            l   | list     )   __list ;;
            q   | quit     )   __quit ;;
                      *  )   __mhelp
    esac
done
}

function __mhelp() {
    echo ""
    echo "a | add       -- Add Music to playlist from Folder"
    echo "> | next      -- Play the next Song in Queue"
    echo "< | previous  -- Play the previous Song in Queue"
    echo "r | resume    -- Resume the song"
    echo "p | play      -- Play a song from Playlist"
    echo "x | remove    -- Remove a song from queue"
    echo "u | pause     -- Pause Music"
    echo "l | list      -- List Songs in Current Queue"
    echo "q | quit      -- Quit"
    echo ""
}


function __help() {
    echo "Usage: $0 [[ -i | --interactive ] [ -h | --host ] [ -p | --port ]]"
}

INTERACTIVE=$1
if [ "$2" ]
then
    HOST=$2
    if [ "$3" ]
    then
        PORT=$3
    fi
fi

case $INTERACTIVE
    in
    -i | --interactive ) __interactive ;;
    -h | --help )       __help
                        exit ;;
                    * ) __help
                        exit 1
esac
